# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: openapi
output: internal/generated/openapi/openapi.go
generate:
  models: true
  echo-server: true
  strict-server: true