# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: oapi
output: internal/generated/oapi/oapi.go
generate:
  models: true
  echo-server: true
  strict-server: true