version: '3'

env:
  IMAGE_NAME: boilerplate-go-backend

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  run:
    deps: [precond]
    cmds:    
      - go run ./cmd/boilerplate-go-backend
  run-with-docker:
    deps: [build-image, precond]
    cmds:
      - docker run -it --rm --name my-running-app -p 1323:1323 $IMAGE_NAME
  precond:
    cmds:
      - docker-compose up -d
  clean:
    cmds:
      - docker-compose down --remove-orphans
  build-image:
    cmds:
      - docker build -t $IMAGE_NAME .
  gen-dotenv:
    cmds:
      - go run ./tools/dotenv_gen/main.go > .env
      - go run ./tools/dotenv_gen/main.go > .env_sample
silent: true

# Learn more at https://taskfile.dev/usage/